language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.10.4
    - otp_release: 23.0
      elixir: 1.11.4
    - otp_release: 24.0
      elixir: 1.12.0
script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
