language: elixir
matrix:
  include:
    - otp_release: 20.3
      elixir: 1.6.6
    - otp_release: 21.1
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.7.3
    - otp_release: 21.1
      elixir: 1.7.3
script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
