language: elixir
matrix:
  include:
    - otp_release: 20.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.8.2
    - otp_release: 22.0
      elixir: 1.8.2
script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
